name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main  # Use 'v4' if that's your branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git info

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Quartz runs best on 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz Site
        run: npx quartz build

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public  # Only deploy built files

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
